//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VogueLink2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Admin_Id { get; set; }
        public string Admin_FName { get; set; }
        public string Admin_LName { get; set; }
        public string Admin_Email { get; set; }
        public string Admin_Pass { get; set; }
        public string Admin_Add { get; set; }
        public string Admin_Phone { get; set; }
        public System.DateTime Admin_DOB { get; set; }
        public int Admin_Salary { get; set; }
        public string Admin_DP { get; set; }
    }
}
