//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VogueLink2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complain
    {
        public int Complains_Id { get; set; }
        public string Complains_Complain { get; set; }
        public int Order_Id { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
