//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VogueLink2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int TransactionId { get; set; }
        public string Invoice_PaymentMethod { get; set; }
        public string Invoice_PaymentStatus { get; set; }
        public int Order_Id { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
