//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VogueLink2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotId { get; set; }
        public int Not_Sender { get; set; }
        public int Not_Rec { get; set; }
        public string Not_Text { get; set; }
        public string Not_Status { get; set; }
    }
}
