//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VogueLink2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.Favourates = new HashSet<Favourate>();
            this.Orders = new HashSet<Order>();
            this.Reviews = new HashSet<Review>();
            this.ProductOrders = new HashSet<ProductOrder>();
        }
    
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public string Product_Brand { get; set; }
        public decimal Product_Price { get; set; }
        public int Product_Quantity { get; set; }
        public string Product_Type { get; set; }
        public string Product_Gender { get; set; }
        public string Product_Material { get; set; }
        public string Product_Size { get; set; }
        public string Product_Color { get; set; }
        public string Product_Img1 { get; set; }
        public string Product_Img2 { get; set; }
        public string Product_Img3 { get; set; }
        public string Product_Img4 { get; set; }
        public int Seller_Id { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile1 { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile2 { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile3 { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile4 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favourate> Favourates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Seller Seller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
    }
}
