//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VogueLink2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrder
    {
        public int PO_Id { get; set; }
        public decimal Order_Price { get; set; }
        public int Order_Quantity { get; set; }
        public string Order_Size { get; set; }
        public int Product_Id { get; set; }
        public int Order_Id { get; set; }
        public int Seller_Id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
