//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VogueLink2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Seller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seller()
        {
            this.Products = new HashSet<Product>();
            this.ProductOrders = new HashSet<ProductOrder>();
        }
    
        public int Seller_Id { get; set; }
        public string Seller_BrandName { get; set; }
        public string Seller_OwnersName { get; set; }
        public string Seller_NationalIdNO { get; set; }
        public string Seller_Email { get; set; }
        public string Seller_Phone { get; set; }
        public string Seller_Pass { get; set; }
        public string Seller_BankAccount { get; set; }
        public string Seller_TradeLicenseNo { get; set; }
        public string Seller_BusinessAddress { get; set; }
        public string Seller_District { get; set; }
        public string Seller_City { get; set; }
        public string Seller_Area { get; set; }
        public string Seller_Status { get; set; }
        public string Seller_DP { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
    }
}
